/*
 * okapia_logo_shape.h — generated by scripts/gen-logo.py, do not edit.
 *
 * The logo in design units, the same numbers the README's SVG and PNGs are
 * drawn from. OkapiaPaintLogo() scales them to the rectangle it is given.
 *
 * Copyright (C) 2026  Jonathan Pepin
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#ifndef _okapia_logo_shape_h
#define _okapia_logo_shape_h

static const float LOGO_CASE_W        = 146.0f;
static const float LOGO_CASE_H        = 176.0f;
static const float LOGO_CASE_RADIUS   = 15.0f;
static const float LOGO_STROKE        = 6.0f;
static const float LOGO_SCREEN_X      = 21.0f;
static const float LOGO_SCREEN_Y      = 21.0f;
static const float LOGO_SCREEN_W      = 104.0f;
static const float LOGO_SCREEN_H      = 80.0f;
static const float LOGO_SCREEN_RADIUS = 8.0f;

// x and y of a band's top at its root, thickness, length, sag: see GfxTaper().
struct TLogoStripe
{
    float fX, fY, fThickness, fLength, fSag;
};

static const TLogoStripe LOGO_STRIPES[] =
{
    { 4.0f, 110.0f, 6.0f, 90.0f, 3.0f },
    { 4.0f, 121.0f, 7.0f, 120.0f, 3.5f },
    { 4.0f, 132.0f, 6.0f, 100.0f, 3.0f },
    { 4.0f, 143.0f, 5.0f, 80.0f, 2.5f },
    { 4.0f, 154.0f, 4.0f, 55.0f, 2.0f }
};

#endif
