#!/usr/bin/env python3
"""Generate the MacRoman <-> Unicode table from Python's own mac_roman codec.

The shared folder sits between a FAT card, whose long names are UTF-8, and a
Macintosh, whose file names are MacRoman. Somebody has to convert, and the
table that does it is 128 entries of the kind nobody proof-reads: a single
wrong code point is one accented letter, in one language, on one card.

So it is not typed. CPython carries Apple's ROMAN.TXT as the mac_roman codec,
which makes the mapping something the build derives rather than something a
person transcribed — the same reasoning as gen-keycodes.py.

  usage: gen-macroman.py <output header>
"""
import sys

out = sys.argv[1]

# 0x00..0x7F is ASCII in both, so only the high half needs a table.
points = []
for byte in range(0x80, 0x100):
    points.append(ord(bytes([byte]).decode("mac_roman")))

lines = [
    "// Generated by scripts/gen-macroman.py — do not edit.",
    "// MacRoman 0x80..0xFF as Unicode code points. The low half is ASCII.",
    "",
    "static const unsigned short MacRomanHigh[128] =",
    "{",
]
for row in range(0, 128, 8):
    entries = ", ".join("0x%04X" % p for p in points[row:row + 8])
    lines.append("    %s," % entries)
lines.append("};")
lines.append("")

with open(out, "w") as f:
    f.write("\n".join(lines))
