#!/usr/bin/env python3
"""Generate the USB HID -> Mac ADB key table from Basilisk II's own keycodes file.

SDL2 scancodes *are* USB HID usage IDs — SDL defines its scancode set from the
HID Keyboard/Keypad page — so the SDL2 section of BasiliskII's keycodes file is
already the table a USB host needs. Deriving it beats typing it: the arrows
alone were wrong when this was written by hand, because their ADB codes differ
from the far more familiar Mac virtual key codes.

  usage: gen-keycodes.py <keycodes file> <output header> [driver]
"""
import sys

path, out = sys.argv[1], sys.argv[2]
driver = sys.argv[3] if len(sys.argv) > 3 else "sdl cocoa"

table = [0xFF] * 256
headers, current, found = [], [], False

for line in open(path, encoding="latin-1"):
    line = line.split("#")[0].split(";")[0].strip()
    if not line:
        continue
    if not line[0].isdigit():
        # A driver string. Several may stack before one table.
        if current:                 # a table just ended: start a new group
            headers, current = [], []
        headers.append(line)
        continue
    scan, mac = (int(x) for x in line.split()[:2])
    current.append((scan, mac))
    if driver in headers:
        found = True
        if 0 <= scan < 256:
            table[scan] = mac

if not found:
    sys.exit("gen-keycodes: no section named %r in %s" % (driver, path))

with open(out, "w") as f:
    f.write("// Generated by scripts/gen-keycodes.py from\n")
    f.write("//   %s, section \"%s\"\n" % (path, driver))
    f.write("// Do not edit: change the source file or the generator.\n")
    f.write("#define OKAPIA_KEYCODES_SOURCE \"%s\"\n" % driver)
    f.write("{\n")
    for row in range(0, 256, 8):
        f.write("    " + ", ".join("0x%02X" % v for v in table[row:row+8]) + ",\n")
    f.write("}\n")

print("gen-keycodes: %d keys from \"%s\"" % (sum(v != 0xFF for v in table), driver))
