#!/usr/bin/env python3
"""Convert the design reference's LVGL icons into the firmware's own format.

boot-menu/ ships the icons as LVGL 9 I1 descriptors — an eight-byte palette
followed by one bit per pixel, rows padded to a byte. The firmware reads plain
rows of bits instead, so the conversion is a re-packing, not a redraw.

Only the ordinary variant is taken. The reference carries a "selected" copy of
each icon because LVGL needed a second palette to draw white on black; here a
selected row is inverted after its contents are drawn, so one bitmap serves both
and half the artwork is unnecessary.

Only the system folders come across. The chrome's own marks — settings, memory,
power — are painted from the rectangle they are given (okapia_theme.cpp), which
keeps them sharp at any scale and means the chrome quotes no system at all.

The system-folder icons are traced from Apple artwork. That is deliberate — the
era belongs to the icons and not to the chrome — but their distribution remains
a decision of its own, separate from the repository's licence.

  usage: gen-icons.py <output .cpp> <source .c> [<source .c> ...]
"""
import re
import sys

# Reference name -> the name the firmware knows it by.
WANTED = {
    "okapia_system_6_icon":  "OkapiaIconSystem6",
    "okapia_system_7_icon":  "OkapiaIconSystem7",
    "okapia_mac_os_8_icon":  "OkapiaIconMacOS8",
    "okapia_mac_os_9_icon":  "OkapiaIconMacOS9",
    # Not traced from anything: drawn here, and reduced by scripts/svg-to-icon.py
    # from assets/icons/cdrom.svg. A medium is not an era, so it is ours to draw.
    "okapia_cdrom_icon":     "OkapiaIconCdrom",
}


def read_icons(path):
    src = open(path, encoding="utf-8", errors="replace").read()
    found = {}

    # The bitmap is named by the descriptor's .data field rather than guessed
    # from the descriptor's own name: Mac OS 8 and Mac OS 9 share one drawing in
    # the reference, and assuming "<name>_map" quietly misses that.
    pattern = (r"const lv_image_dsc_t\s+(\w+)\s*=\s*\{.*?"
               r"\.w\s*=\s*(\d+),\s*\.h\s*=\s*(\d+),.*?\.data\s*=\s*(\w+),")
    for name, width, height, symbol in re.findall(pattern, src, re.S):
        if name not in WANTED:
            continue
        width, height = int(width), int(height)
        if width > 32:
            raise SystemExit(f"{name}: {width} px wide, the firmware holds 32 at most")

        m = re.search(r"uint8_t\s+" + symbol + r"\[\]\s*=\s*\{(.*?)\};", src, re.S)
        if m is None:
            raise SystemExit(f"{name}: no bitmap {symbol}")
        data = [int(v, 0) for v in re.findall(r"0[xX][0-9a-fA-F]+", m.group(1))]

        stride = (width + 7) // 8
        data = data[8:]                 # drop the two-entry palette
        if len(data) < stride * height:
            raise SystemExit(f"{name}: {len(data)} bytes for {stride * height}")

        rows = []
        for y in range(height):
            value = 0
            for b in range(stride):
                value = (value << 8) | data[y * stride + b]
            # The row is packed left-aligned in stride*8 bits; the firmware wants
            # it left-aligned in exactly `width` bits.
            rows.append(value >> (stride * 8 - width))
        found[name] = (width, height, rows)

    return found


def main():
    if len(sys.argv) < 3:
        raise SystemExit(__doc__)
    out_path, sources = sys.argv[1], sys.argv[2:]

    icons = {}
    for path in sources:
        icons.update(read_icons(path))

    missing = [n for n in WANTED if n not in icons]
    if missing:
        raise SystemExit("not found: " + ", ".join(missing))

    with open(out_path, "w", encoding="utf-8") as out:
        out.write("// Generated by scripts/gen-icons.py — do not edit.\n")
        out.write("//\n// Re-packed from the LVGL descriptors in boot-menu/.\n")
        out.write("// The system-folder icons are traced from Apple artwork; see that\n")
        out.write("// directory's README and planification.md §7.12.\n\n")
        # okapia_icons.h, which carries the extern declarations. Without a prior
        # extern a namespace-scope const has *internal* linkage in C++: the
        # object compiles clean and links to nothing.
        out.write('#include "okapia_icons.h"\n\n')
        for name, ours in WANTED.items():
            width, height, rows = icons[name]
            out.write(f"// {ours}: {width}x{height}, from {name}\n")
            out.write(f"static const unsigned s_{ours}Rows[] =\n{{\n")
            for i in range(0, len(rows), 6):
                out.write("\t" + ", ".join(f"0x{r:08X}" for r in rows[i:i + 6]) + ",\n")
            out.write("};\n")
            out.write(f"const TGlyphImage {ours} = {{ {width}, {height}, s_{ours}Rows }};\n\n")


main()
