#!/usr/bin/env python3
"""Draw Okapia's logo: the drawing, its PNG sizes, and the table the firmware paints from.

A compact Macintosh whose screen is the okapi's dark body and whose chin carries
the stripes of its hindquarters. The geometry below is the only copy of it: the
SVG, every PNG and the boot menu's painter (OkapiaPaintLogo) all come from these
numbers, so the logo on the README and the logo on the screen cannot drift.

  usage: gen-logo.py [<repository root>]

Writes assets/logo/okapia.svg, assets/logo/okapia-<size>.png and
src/firmware/okapia_logo_shape.h. No dependency: the PNGs are rasterised here
and compressed with zlib, since neither PIL nor rsvg-convert is installed on a
machine that builds this.

A stripe is a tapered band laid from the case's left edge: at a fraction u of
its length its centre has dropped by sag*u^2 and its thickness is
t*(1 - u^2.25). GfxTaper() in okapia_gfx.cpp computes the same law, and the two
must change together.
"""
import math
import os
import struct
import sys
import zlib

# Design units. The case's outer edge, stroke included.
CASE_W, CASE_H = 146.0, 176.0
CASE_RADIUS = 15.0
STROKE = 6.0
SCREEN = (21.0, 21.0, 104.0, 80.0)
SCREEN_RADIUS = 8.0
# x, y of the band's top at its root, thickness, length, sag.
STRIPES = [
    (4.0, 110.0, 6.0,  90.0, 3.0),
    (4.0, 121.0, 7.0, 120.0, 3.5),
    (4.0, 132.0, 6.0, 100.0, 3.0),
    (4.0, 143.0, 5.0,  80.0, 2.5),
    (4.0, 154.0, 4.0,  55.0, 2.0),
]
PNG_SIZES = [16, 32, 48, 64, 128, 256, 512, 1024]


def taper(u):
    return 1.0 - u * u * math.sqrt(math.sqrt(u))


def round_box(x, y, bx, by, bw, bh, r):
    """Signed distance to a rounded rectangle, negative inside."""
    hw, hh = bw / 2, bh / 2
    dx = abs(x - (bx + hw)) - (hw - r)
    dy = abs(y - (by + hh)) - (hh - r)
    outside = math.hypot(max(dx, 0.0), max(dy, 0.0))
    return (outside if max(dx, dy) > 0 else max(dx, dy)) - r


def in_stripe(x, y, stripe):
    x0, y0, t, length, sag = stripe
    u = (x - x0) / length
    if u < 0.0 or u > 1.0:
        return False
    return abs(y - (y0 + t / 2 + sag * u * u)) <= t / 2 * taper(u)


# ---------------------------------------------------------------- the drawing

def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def stripe_path(stripe, steps=48):
    x0, y0, t, length, sag = stripe
    # Denser towards the tip, where the outline turns.
    us = [1.0 - (1.0 - i / steps) ** 2 for i in range(steps + 1)]
    top = [(x0 + length * u, y0 + t / 2 + sag * u * u - t / 2 * taper(u)) for u in us]
    bottom = [(x0 + length * u, y0 + t / 2 + sag * u * u + t / 2 * taper(u)) for u in reversed(us[:-1])]
    points = top + bottom
    return "M" + " L".join(f"{f(x)} {f(y)}" for x, y in points) + "Z"


def svg():
    ox = (CASE_H - CASE_W) / 2
    inner = STROKE
    sx, sy, sw, sh = SCREEN
    stripes = "\n    ".join(f'<path d="{stripe_path(s)}"/>' for s in STRIPES)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {f(CASE_H)} {f(CASE_H)}" width="{f(CASE_H)}" height="{f(CASE_H)}">
  <title>Okapia</title>
  <!-- Generated by scripts/gen-logo.py — do not edit. -->
  <g transform="translate({f(ox)} 0)">
    <rect width="{f(CASE_W)}" height="{f(CASE_H)}" rx="{f(CASE_RADIUS)}" fill="#000"/>
    <rect x="{f(inner)}" y="{f(inner)}" width="{f(CASE_W - 2 * inner)}" height="{f(CASE_H - 2 * inner)}" rx="{f(CASE_RADIUS - inner)}" fill="#fff"/>
    <g fill="#000">
    {stripes}
    </g>
    <rect x="{f(sx)}" y="{f(sy)}" width="{f(sw)}" height="{f(sh)}" rx="{f(SCREEN_RADIUS)}" fill="#000"/>
  </g>
</svg>
"""


# ------------------------------------------------------------------ the PNGs

def render(size):
    """Grey and alpha per pixel. The case is opaque and the corners around it
    are transparent, so the logo sits on any background."""
    k = size / CASE_H
    # The case's width is rounded to whole pixels and so is its offset: at
    # sixteen or thirty-two pixels an edge falling between two columns is a
    # grey column, and the stroke is only a pixel wide to begin with.
    width = round(CASE_W * k)
    kx = width / CASE_W
    ox = (size - width) // 2
    sx, sy, sw, sh = SCREEN
    samples = 4
    rows = []
    for py in range(size):
        row = bytearray()
        for px in range(size):
            x = (px + 0.5 - ox) / kx
            y = (py + 0.5) / k
            value, alpha = 0.0, 0.0

            def paint(grey, cover):
                nonlocal value, alpha
                if cover <= 0.0:
                    return
                out = cover + alpha * (1.0 - cover)
                value = (grey * cover + value * alpha * (1.0 - cover)) / out
                alpha = out

            paint(0.0, min(1.0, max(0.0, 0.5 - round_box(x, y, 0, 0, CASE_W, CASE_H, CASE_RADIUS) * k)))
            paint(1.0, min(1.0, max(0.0, 0.5 - round_box(x, y, STROKE, STROKE, CASE_W - 2 * STROKE,
                                                          CASE_H - 2 * STROKE,
                                                          CASE_RADIUS - STROKE) * k)))
            if STRIPES[0][1] - 1 <= y <= STRIPES[-1][1] + STRIPES[-1][2] + STRIPES[-1][4] + 1:
                hits = 0
                for j in range(samples):
                    for i in range(samples):
                        qx = x + ((i + 0.5) / samples - 0.5) / kx
                        qy = y + ((j + 0.5) / samples - 0.5) / k
                        if any(in_stripe(qx, qy, s) for s in STRIPES):
                            hits += 1
                paint(0.0, hits / (samples * samples))
            paint(0.0, min(1.0, max(0.0, 0.5 - round_box(x, y, sx, sy, sw, sh, SCREEN_RADIUS) * k)))
            row += bytes((round(value * 255), round(alpha * 255)))
        rows.append(bytes(row))
    return rows


def png(size, rows):
    def chunk(kind, data):
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
    raw = b"".join(b"\x00" + r for r in rows)
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 4, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9))
            + chunk(b"IEND", b""))


# --------------------------------------------------------- the firmware's table

def cf(v):
    """A C float literal: "4f" is not one, "4.0f" is."""
    text = f(v)
    return (text if "." in text else text + ".0") + "f"


def header():
    lines = ",\n".join(f"    {{ {cf(x)}, {cf(y)}, {cf(t)}, {cf(l)}, {cf(s)} }}" for x, y, t, l, s in STRIPES)
    sx, sy, sw, sh = SCREEN
    return f"""/*
 * okapia_logo_shape.h — generated by scripts/gen-logo.py, do not edit.
 *
 * The logo in design units, the same numbers the README's SVG and PNGs are
 * drawn from. OkapiaPaintLogo() scales them to the rectangle it is given.
 *
 * Copyright (C) 2026  Jonathan Pepin
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#ifndef _okapia_logo_shape_h
#define _okapia_logo_shape_h

static const float LOGO_CASE_W        = {cf(CASE_W)};
static const float LOGO_CASE_H        = {cf(CASE_H)};
static const float LOGO_CASE_RADIUS   = {cf(CASE_RADIUS)};
static const float LOGO_STROKE        = {cf(STROKE)};
static const float LOGO_SCREEN_X      = {cf(sx)};
static const float LOGO_SCREEN_Y      = {cf(sy)};
static const float LOGO_SCREEN_W      = {cf(sw)};
static const float LOGO_SCREEN_H      = {cf(sh)};
static const float LOGO_SCREEN_RADIUS = {cf(SCREEN_RADIUS)};

// x and y of a band's top at its root, thickness, length, sag: see GfxTaper().
struct TLogoStripe
{{
    float fX, fY, fThickness, fLength, fSag;
}};

static const TLogoStripe LOGO_STRIPES[] =
{{
{lines}
}};

#endif
"""


def main(argv):
    root = argv[1] if len(argv) > 1 else os.path.join(os.path.dirname(__file__), "..")
    out = os.path.join(root, "assets", "logo")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "okapia.svg"), "w", encoding="utf-8") as fh:
        fh.write(svg())
    for size in PNG_SIZES:
        with open(os.path.join(out, f"okapia-{size}.png"), "wb") as fh:
            fh.write(png(size, render(size)))
        print(f"assets/logo/okapia-{size}.png")
    with open(os.path.join(root, "src", "firmware", "okapia_logo_shape.h"), "w", encoding="utf-8") as fh:
        fh.write(header())
    print("assets/logo/okapia.svg, src/firmware/okapia_logo_shape.h")


if __name__ == "__main__":
    main(sys.argv)
