#!/usr/bin/env python3
# Copyright (C) 2026  Jonathan Pepin
# SPDX-License-Identifier: GPL-3.0-or-later
"""Turn the translation table into C++ tables and an enumeration.

The strings are typed once, in a file anyone can edit and diff, and the code
that uses them cannot drift out of step with it: the identifiers are generated
from the same rows as the text, so a key that is renamed or removed stops the
build rather than showing an empty label at run time.

Same habit as scripts/gen-keycodes.py and gen-font.py — nothing about the
interface is typed twice.

    usage: gen-strings.py <out.cpp> <out-ids.h> <strings.tsv>
"""
import sys


def identifier(key):
    return "Str" + "".join(part.capitalize() for part in key.split("_"))


def escape(text):
    out = []
    for ch in text:
        if ch == "\\" or ch == '"':
            out.append("\\" + ch)
        else:
            out.append(ch)
    return "".join(out)


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    out_cpp, out_h, source = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(source, encoding="utf-8") as f:
        rows = [line.rstrip("\n").split("\t") for line in f
                if line.strip() and not line.startswith("#")]

    header, rows = rows[0], rows[1:]
    if header[0] != "key":
        sys.exit("first column must be 'key'")
    languages = header[1:]

    for n, row in enumerate(rows, 2):
        if len(row) != len(header):
            sys.exit("%s: row %d has %d columns, expected %d"
                     % (source, n, len(row), len(header)))

    seen = set()
    for row in rows:
        if row[0] in seen:
            sys.exit("%s: duplicate key %s" % (source, row[0]))
        seen.add(row[0])

    with open(out_h, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen-strings.py from %s. Do not edit.\n"
                % source)
        f.write("#ifndef _okapia_strings_ids_h\n#define _okapia_strings_ids_h\n\n")
        f.write("enum TStringId\n{\n")
        for row in rows:
            f.write("    %s,\n" % identifier(row[0]))
        f.write("    StringCount\n};\n\n")
        f.write("enum TLanguage\n{\n")
        for lang in languages:
            f.write("    Lang%s,\n" % lang.upper())
        f.write("    LanguageCount\n};\n\n")
        f.write("#endif\n")

    with open(out_cpp, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen-strings.py from %s. Do not edit.\n"
                % source)
        f.write('#include "okapia_strings.h"\n\n')
        f.write("const char *const OkapiaStringTable[LanguageCount][StringCount] =\n{\n")
        for i, lang in enumerate(languages):
            f.write("    {   // %s\n" % lang)
            for row in rows:
                f.write('        "%s",\n' % escape(row[i + 1]))
            f.write("    },\n")
        f.write("};\n\n")
        f.write("const char *const OkapiaLanguageCode[LanguageCount] =\n{\n")
        for lang in languages:
            f.write('    "%s",\n' % lang)
        f.write("};\n")


if __name__ == "__main__":
    main()
