#!/usr/bin/env bash
# Install the host tools needed to build Okapia. Idempotent: safe to re-run.
set -euo pipefail

TOOLCHAIN_VERSION="15.2.rel1"
TOOLCHAIN_NAME="arm-gnu-toolchain-${TOOLCHAIN_VERSION}-darwin-arm64-aarch64-none-elf"
TOOLCHAIN_SHA256="37084c99bc05fda43a6c48900c638ae4fd6d93e2287ceb3e9bcda55437f1aadd"
TOOLCHAIN_URL="https://developer.arm.com/-/media/Files/downloads/gnu/${TOOLCHAIN_VERSION}/binrel/${TOOLCHAIN_NAME}.tar.xz"
TOOLCHAIN_ROOT="${TOOLCHAIN_ROOT:-$HOME/toolchains}"
TOOLCHAIN_DIR="${TOOLCHAIN_ROOT}/${TOOLCHAIN_NAME}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/scripts/env.sh"

say() { printf '\n==> %s\n' "$1"; }

[ "$(uname -s)" = "Darwin" ] || { echo "This script targets macOS. On Linux, use your package manager and the linux toolchain from developer.arm.com." >&2; exit 1; }
[ "$(uname -m)" = "arm64" ] || { echo "Apple Silicon expected: ARM publishes no darwin-x86_64 build for ${TOOLCHAIN_VERSION}." >&2; exit 1; }

# --- Homebrew packages -------------------------------------------------------
say "Homebrew packages"
command -v brew >/dev/null || { echo "Homebrew is required: https://brew.sh" >&2; exit 1; }
for pkg in qemu make dtc; do
    if brew list --formula "$pkg" >/dev/null 2>&1; then
        echo "  $pkg already installed"
    else
        echo "  installing $pkg"
        brew install "$pkg"
    fi
done

# --- ARM GNU toolchain -------------------------------------------------------
# Not in Homebrew. This is the exact version Circle and circle-stdlib are tested
# with; Homebrew's aarch64-elf-gcc is a different prefix and an untested version.
say "ARM GNU toolchain ${TOOLCHAIN_VERSION} (aarch64-none-elf)"
if [ -x "${TOOLCHAIN_DIR}/bin/aarch64-none-elf-gcc" ]; then
    echo "  already installed at ${TOOLCHAIN_DIR}"
else
    mkdir -p "${TOOLCHAIN_ROOT}"
    ARCHIVE="${TOOLCHAIN_ROOT}/${TOOLCHAIN_NAME}.tar.xz"
    if [ ! -f "${ARCHIVE}" ]; then
        echo "  downloading 81 MB"
        curl -fL --progress-bar "${TOOLCHAIN_URL}" -o "${ARCHIVE}"
    fi
    echo "  verifying checksum"
    echo "${TOOLCHAIN_SHA256}  ${ARCHIVE}" | shasum -a 256 -c - || {
        echo "Checksum mismatch. Delete ${ARCHIVE} and re-run." >&2; exit 1; }
    echo "  extracting"
    tar -xf "${ARCHIVE}" -C "${TOOLCHAIN_ROOT}"
    # ARM's binaries are unsigned: without this macOS refuses to run them.
    echo "  clearing quarantine attribute"
    xattr -dr com.apple.quarantine "${TOOLCHAIN_DIR}" 2>/dev/null || true
    rm -f "${ARCHIVE}"
fi

# --- Environment file --------------------------------------------------------
say "Environment file"
cat > "${ENV_FILE}" <<ENV
# Generated by scripts/install-tools.sh — source this before building.
export OKAPIA_TOOLCHAIN="${TOOLCHAIN_DIR}"
export PATH="\${OKAPIA_TOOLCHAIN}/bin:\$PATH"
export TOOLCHAIN_PREFIX="aarch64-none-elf-"
# macOS ships GNU Make 3.81; Homebrew's is 4.x and installs as gmake.
export MAKE="\$(command -v gmake || command -v make)"
ENV
echo "  wrote ${ENV_FILE}"

# --- Verify ------------------------------------------------------------------
say "Verification"
# shellcheck source=/dev/null
. "${ENV_FILE}"
aarch64-none-elf-gcc --version | head -1
"${MAKE}" --version | head -1
qemu-system-aarch64 --version | head -1
qemu-system-aarch64 -M help | grep -q raspi3b && echo "qemu: raspi3b machine available" || echo "WARNING: qemu has no raspi3b machine"

say "Done. Run 'source scripts/env.sh' in each new shell, then scripts/bootstrap.sh."
